services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker \
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    volumes: 
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    # Build the image from the Dockerfile in the current directory
    build: ./backend

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_SERVER=db
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./backend
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - ./backend/.venv

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./backend/uv.lock
        
        - action: rebuild
          path: ./backend/Dockerfile
volumes:
  db: