"""add thumbnail to movie

Revision ID: 64af06ff0e78
Revises: 7f22db3f141a
Create Date: 2025-09-25 09:15:56.220884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64af06ff0e78'
down_revision: Union[str, Sequence[str], None] = '7f22db3f141a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'thumbnail')
    # ### end Alembic commands ###
