"""cascade delete on junction tables

Revision ID: 7f22db3f141a
Revises: 8a5d93e7bfc6
Create Date: 2025-09-08 08:00:38.196318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f22db3f141a'
down_revision: Union[str, Sequence[str], None] = '8a5d93e7bfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('moive_actors_link_actor_id_fkey'), 'moive_actors_link', type_='foreignkey')
    op.drop_constraint(op.f('moive_actors_link_movie_id_fkey'), 'moive_actors_link', type_='foreignkey')
    op.create_foreign_key(None, 'moive_actors_link', 'actor', ['actor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'moive_actors_link', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint(op.f('movie_genre_link_movie_id_fkey'), 'movie_genre_link', type_='foreignkey')
    op.drop_constraint(op.f('movie_genre_link_genre_id_fkey'), 'movie_genre_link', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genre_link', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_genre_link', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_genre_link', type_='foreignkey')
    op.drop_constraint(None, 'movie_genre_link', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genre_link_genre_id_fkey'), 'movie_genre_link', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(op.f('movie_genre_link_movie_id_fkey'), 'movie_genre_link', 'movie', ['movie_id'], ['id'])
    
    op.drop_constraint(None, 'moive_actors_link', type_='foreignkey')
    op.drop_constraint(None, 'moive_actors_link', type_='foreignkey')
    op.create_foreign_key(op.f('moive_actors_link_movie_id_fkey'), 'moive_actors_link', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('moive_actors_link_actor_id_fkey'), 'moive_actors_link', 'actor', ['actor_id'], ['id'])
    
    # ### end Alembic commands ###
